### PR TITLE
Add support for Laravel 7

### PR DESCRIPTION
**Pull request by henryavila**

### CODE REVIEW

**Comment by LorenzoSapora** [comment]
Bump @bolechen

**Comment by bolechen** [comment]
Can it also support Laravel6 and Laravel7? @henryavila

**Comment by LorenzoSapora** [comment]
@bolechen If you want to continue to support Laravel 5-6, fix the line:

```json
"laravel/nova": "^2.0|^3.0",
"spatie/laravel-activitylog": "^3.9.2"
```

**Comment by LorenzoSapora** [comment]
Correction:

```json
"laravel/nova": "^2.0|^3.0",
"spatie/laravel-activitylog": "^3.9.1"
```

**Comment by bolechen** [comment]
> Correction:
> 
> ```json
> "laravel/nova": "^2.0|^3.0",
> "spatie/laravel-activitylog": "^3.9.1"
> ```

got it,  🍻

**Pull request merged**
